# Generated by Django 5.1.3 on 2024-11-29 20:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_empresa', models.CharField(max_length=100)),
                ('img_empresa', models.ImageField(default='default.jpg', upload_to='empresas/')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_plano', models.CharField(max_length=100)),
                ('img_plano', models.ImageField(default='default.jpg', upload_to='planos/')),
                ('descricao_plano', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seguro', models.CharField(max_length=100)),
                ('img_seguro', models.ImageField(default='default.jpg', upload_to='seguros/')),
                ('descricao_seguro', models.TextField(max_length=1000)),
            ],
        ),
    ]
